# Generated by Django 5.2.1 on 2025-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_token_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
